version: '3.8'

services:
  # Основная база данных
  postgres:
    image: postgres:14
    container_name: wallet-postgres
    env_file:
      - config.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  # База для интеграционных тестов
  postgres_test:
    image: postgres:14
    container_name: wallet-test-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres__
      POSTGRES_DB: wallet_test
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=100"]

  # Приложение
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - config.env

volumes:
  pgdata:
  pgdata_test:
