services:
  # Основная база данных
  postgres:
    image: postgres:14
    container_name: wallet-postgres
    env_file:
      - config.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  # Приложение
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - config.env

volumes:
  pgdata: